# Generated by Django 5.2.14 on 2026-06-01 18:36

import chips.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('iccid', models.CharField(blank=True, max_length=22)),
                ('imagem', models.ImageField(upload_to=chips.models.chip_imagem_path)),
                ('imagem_tentativa_2', models.ImageField(blank=True, null=True, upload_to=chips.models.chip_imagem_path)),
                ('tentativas', models.PositiveSmallIntegerField(default=1)),
                ('status_leitura', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
                ('status_revisao', models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando_aprovacao', max_length=20)),
                ('corrigido_manualmente', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='lotes.lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips_lidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chip',
                'verbose_name_plural': 'Chips',
                'ordering': ['lote', 'sequencia'],
            },
        ),
    ]
