# Generated by Django 5.2.14 on 2026-06-01 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('criar_lote', 'Criar lote'), ('leitura', 'Leitura de ICCID'), ('correcao', 'Correção manual'), ('remover_chip', 'Remover chip'), ('aprovar_lote', 'Aprovar lote'), ('cancelar_lote', 'Cancelar lote'), ('exportar', 'Exportar lote')], max_length=50)),
                ('iccid', models.CharField(blank=True, max_length=22)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-data_hora'],
            },
        ),
    ]
