# Generated by Django 5.2.14 on 2026-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='acao',
            field=models.CharField(choices=[('criar_lote', 'Criar lote'), ('renomear_lote', 'Renomear lote'), ('leitura', 'Leitura de ICCID'), ('correcao', 'Correção manual'), ('remover_chip', 'Remover chip'), ('aprovar_lote', 'Aprovar lote'), ('cancelar_lote', 'Cancelar lote'), ('exportar', 'Exportar lote')], max_length=50),
        ),
    ]
